#!/data/data/com.termux/files/usr/bin/bash

# ╔══════════════════════════════════════════════════╗
# ║  SIMULACIÓN COMPLETA — Flujo real del cliente   ║
# ╚══════════════════════════════════════════════════╝

R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'
B='\033[0;34m'; C='\033[0;36m'; M='\033[0;35m'
W='\033[1;37m'; NC='\033[0m'

clear
echo ""
echo -e "${C}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${C}║${W}  🧪 SIMULACIÓN: Soy un cliente que compró       ${C}║${NC}"
echo -e "${C}║${W}     el CRM IA Hotelero                          ${C}║${NC}"
echo -e "${C}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${Y}Presioná Enter en cada paso para avanzar${NC}"
read -p ""

# ═══════════════════════════════════════════
# FASE 0: Email de compra
# ═══════════════════════════════════════════
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${B}  FASE 0: Recibí el email de compra${NC}"
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  📧 Abrí Gmail en mi celular"
echo -e "  📧 Veo el email:"
echo ""
echo -e "  ┌──────────────────────────────────────────┐"
echo -e "  │  De: soporte@oficinabarreal.com          │"
echo -e "  │  Asunto: 🎉 ¡Tu CRM IA Hotelero está     │"
echo -e "  │          listo! Descargá tu curso        │"
echo -e "  │                                          │"
echo -e "  │  [DESCARGAR CURSO - $99]                 │"
echo -e "  │                                          │"
echo -e "  │  Incluye: CRM + Zira + Instagram +       │"
echo -e "  │  WhatsApp + Revista Digital + Todo       │"
echo -e "  └──────────────────────────────────────────┘"
echo ""
read -p "  → Toco 'DESCARGAR CURSO'...  [Enter]"
echo ""

# ═══════════════════════════════════════════
# FASE 1: Descarga y descompresión
# ═══════════════════════════════════════════
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${B}  FASE 1: Descargo y descomprimo el .zip${NC}"
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  📥 Android me pregunta: '¿Dónde guardar?'"
echo -e "  📥 Eligo: Descargas"
echo -e "  📥 Se descarga: curso-crm.zip"
echo ""
echo -e "  📂 Voy a la app 'Archivos' de mi celular"
echo -e "  📂 Busco 'curso-crm.zip' en Descargas"
echo -e "  📂 Lo toco → me da opciones"
echo -e "  📂 Elijo 'Extraer' o 'Descomprimir'"
echo -e "  📂 Se crea la carpeta: curso-crm/"
echo ""
read -p "  → Entró a la carpeta curso-crm/...  [Enter]"
echo ""

# ═══════════════════════════════════════════
# FASE 2: El cliente ve los archivos
# ═══════════════════════════════════════════
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${B}  FASE 2: Veo el contenido de la carpeta${NC}"
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  📁 curso-crm/"
echo -e "  ├── ${G}1_PASOS_AQUI.html${NC}  ← ¡ESTO MIRE PRIMERO!"
echo -e "  ├── index.html"
echo -e "  ├── install.sh"
echo -e "  ├── .env.example"
echo -e "  ├── PRODUCT_README.md"
echo -e "  ├── core-crm/"
echo -e "  ├── docs/"
echo -e "  └── config/"
echo ""
echo -e "  ${Y}→ Toco '1_PASOS_AQUI.html'${NC}"
echo -e "  ${Y}→ Se abre en el navegador de mi celular${NC}"
echo ""
read -p "  → Se abrió la guía en el navegador...  [Enter]"
echo ""

# ═══════════════════════════════════════════
# FASE 3: Guía visual (1_PASOS_AQUI.html)
# ═══════════════════════════════════════════
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${B}  FASE 3: Leo la guía en el navegador${NC}"
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  🌐 Veo la página:"
echo ""
echo -e "  ┌──────────────────────────────────────────┐"
echo -e "  │  🏔️ CRM IA Hotelero                      │"
echo -e "  │  Tu posada se administra sola             │"
echo -e "  │                                          │"
echo -e "  │  👆 EMPEZÁ ACÁ                           │"
echo -e "  │                                          │"
echo -e "  │  Paso 0: ¿Qué compraste?                 │"
echo -e "  │  Paso 1: Descargá F-Droid                │"
echo -e "  │  Paso 2: Instalá Termux                  │"
echo -e "  │  Paso 3: Dale permisos                   │"
echo -e "  │  Paso 4: Entrá a la carpeta              │"
echo -e "  │  Paso 5: Instalá todo                    │"
echo -e "  │  Paso 6: Configurá tu asistente IA       │"
echo -e "  │  Paso 7: Iniciá a Zira                   │"
echo -e "  │                                          │"
echo -e "  │  [Botones de copiar en cada comando]     │"
echo -e "  └──────────────────────────────────────────┘"
echo ""
echo -e "  ${Y}→ Leo cada paso con calma${NC}"
echo -e "  ${Y}→ Presiono 'Copiar' en cada comando${NC}"
echo ""
read -p "  → Terminé de leer la guía...  [Enter]"
echo ""

# ═══════════════════════════════════════════
# FASE 4: Instalo F-Droid y Termux
# ═══════════════════════════════════════════
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${B}  FASE 4: Instalo F-Droid y Termux${NC}"
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  📱 Voy a f-droid.org en Chrome"
echo -e "  📱 Descargo F-Droid APK"
echo -e "  📱 Android: '¿Instalar app de origen desconocido?'"
echo -e "  📱 Voy a Configurar → activo 'Permitir desde esta fuente'"
echo -e "  📱 Instalo F-Droid"
echo ""
echo -e "  📱 Abro F-Droid"
echo -e "  📱 Busco 'Termux'"
echo -e "  📱 Instalo Termux"
echo -e "  📱 Abro Termux"
echo -e "  📱 Veo pantalla negra con \$"
echo ""
echo -e "  ${G}✓ F-Droid instalado${NC}"
echo -e "  ${G}✓ Termux instalado${NC}"
echo ""
read -p "  → Termux está abierto...  [Enter]"
echo ""

# ═══════════════════════════════════════════
# FASE 5: Primeros comandos
# ═══════════════════════════════════════════
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${B}  FASE 5: Mis primeros comandos en Termux${NC}"
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ${Y}→ Toco la pantalla, aparece el teclado${NC}"
echo ""
echo -e "  \$ ${C}termux-setup-storage${NC}"
echo -e "  [Popup: '¿Permitir acceso a archivos?'] → Allow"
echo -e "  ${G}✓ Permisos dados${NC}"
echo ""
echo -e "  \$ ${C}cd ~/storage/downloads/curso-crm${NC}"
echo -e "  ${G}✓ Entré a la carpeta del curso${NC}"
echo ""
echo -e "  \$ ${C}ls${NC}"
echo -e "  1_PASOS_AQUI.html  install.sh  core-crm/  docs/"
echo ""
read -p "  → Estoy dentro de la carpeta...  [Enter]"
echo ""

# ═══════════════════════════════════════════
# FASE 6: Instalación automática
# ═══════════════════════════════════════════
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${B}  FASE 6: Ejecuto install.sh${NC}"
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  \$ ${C}chmod +x install.sh${NC}"
echo -e "  \$ ${C}./install.sh${NC}"
echo ""
echo -e "  ╔══════════════════════════════════════════╗"
echo -e "  ║  🏔️  CRM IA HOTELERO — Instalador       ║"
echo -e "  ╚══════════════════════════════════════════╝"
echo ""
echo -e "  Paso 1/8: Permisos de almacenamiento    ${G}✓${NC}"
echo -e "  Paso 2/8: Actualizando Termux           ${G}✓${NC}"
echo -e "  Paso 3/8: Instalando dependencias       ${G}✓${NC}"
echo -e "  Paso 4/8: Instalando librerías Python   ${G}✓${NC}"
echo -e "  Paso 5/8: Instalando Hermes Agent       ${G}✓${NC}"
echo ""
echo -e "  ${W}━━━ Paso 6/8: Configurar tu asistente IA ━━━${NC}"
echo ""
echo -e "  ${W}Zira necesita un proveedor de IA:${NC}"
echo ""
echo -e "  ${C}1${NC}) NVIDIA (gratis, recomendado)"
echo -e "  ${C}2${NC}) Google AI / Gemini (gratis)"
echo -e "  ${C}3${NC}) OpenRouter (gratis)"
echo -e "  ${C}4${NC}) Ya tengo API key"
echo -e "  ${C}5${NC}) Configurar después"
echo ""
echo -e "  ${Y}→ Elijo: 1 (NVIDIA)${NC}"
echo ""
echo -e "  ${Y}→ Me da instrucciones:${NC}"
echo -e "  1. Abrí build.nvidia.com"
echo -e "  2. Creá cuenta (uso Google)"
echo -e "  3. Andá a org.ngc.nvidia.com/setup/api-keys"
echo -e "  4. Copiá tu API key (nvapi-...)"
echo ""
echo -e "  ${Y}→ Salgo de Termux, abro Chrome${NC}"
echo -e "  ${Y}→ Creo cuenta en NVIDIA${NC}"
echo -e "  ${Y}→ Copio la API key${NC}"
echo -e "  ${Y}→ Vuelvo a Termux${NC}"
echo ""
echo -e "  Pegá tu API Key: ${C}nvapi-xxxxxxxxxxxx${NC}"
echo ""
echo -e "  ${G}✓ Proveedor configurado: nvidia${NC}"
echo -e "  ${G}✓ Modelo: z-ai/glm-5.1${NC}"
echo ""
echo -e "  Paso 7/8: Configurando Zira CRM Bot     ${G}✓${NC}"
echo -e "  Paso 8/8: Configurando el proyecto       ${G}✓${NC}"
echo ""
echo -e "  ╔══════════════════════════════════════════╗"
echo -e "  ║  🎉 ¡INSTALACIÓN COMPLETADA!             ║"
echo -e "  ╚══════════════════════════════════════════╝"
echo ""
echo -e "  Para iniciar a Zira, escribí: ${G}hermes${NC}"
echo ""
read -p "  → Todo instalado...  [Enter]"
echo ""

# ═══════════════════════════════════════════
# FASE 7: Primer contacto con Zira
# ═══════════════════════════════════════════
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${B}  FASE 7: Conozco a Zira${NC}"
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  \$ ${C}hermes${NC}"
echo ""
echo -e "  ╔══════════════════════════════════════════╗"
echo -e "  ║  🤖 Zira — Asistente Virtual CRM        ║"
echo -e "  ╚══════════════════════════════════════════╝"
echo ""
echo -e "  ${M}Zira:${NC} ¡Hola! Soy Zira, tu asistente virtual."
echo -e "        Vi que acabás de instalar el CRM."
echo -e "        ¿En qué puedo ayudarte?"
echo ""
echo -e "  ${W}Yo:${NC} Hola Zira, ¿qué hago ahora?"
echo ""
echo -e "  ${M}Zira:${NC} ¡Perfecto! Vamos a configurar tu CRM"
echo -e "        paso a paso. Primero necesitamos"
echo -e "        conectar tu base de datos en Google."
echo ""
echo -e "        ¿Querés que te explique cómo crear"
echo -e "        un proyecto en Google Cloud?"
echo ""
echo -e "  ${W}Yo:${NC} Sí, por favor"
echo ""
echo -e "  ${M}Zira:${NC} ¡Genial! Abrí tu navegador y entrá a"
echo -e "        console.cloud.google.com"
echo ""
echo -e "        Te voy guiando en cada paso..."
echo ""
read -p "  → Zira me está guiando...  [Enter]"
echo ""

# ═══════════════════════════════════════════
# FASE 8: Configuración guiada
# ═══════════════════════════════════════════
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${B}  FASE 8: Zira me guía en la configuración${NC}"
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ${M}Zira:${NC} Te voy a ir diciendo qué hacer."
echo -e "        Si te trabás, preguntame."
echo -e "        ¡Vamos!"
echo ""
echo -e "  ┌─ Google Cloud ─────────────────────────┐"
echo -e "  │ ${M}Zira:${NC} Andá a console.cloud.google.com   │"
echo -e "  │ Yo: Ok                                  │"
echo -e "  │ ${M}Zira:${NC} Creá un proyecto nuevo             │"
echo -e "  │ Yo: Listo                               │"
echo -e "  │ ${M}Zira:${NC} Buscá 'Sheets API' y habilitala    │"
echo -e "  │ Yo: Ya está                             │"
echo -e "  │ ${M}Zira:${NC} Ahora creamos la Cuenta de Servicio │"
echo -e "  │ Yo: Dale                                │"
echo -e "  │ ${M}Zira:${NC} Descargá el archivo JSON           │"
echo -e "  │ Yo: Listo                               │"
echo -e "  │ ${M}Zira:${NC} Compartí la hoja con ese email     │"
echo -e "  │ Yo: ¡Listo!                             │"
echo -e "  │ ${G}✓ Google Cloud conectado ✓${NC}            │"
echo -e "  └─────────────────────────────────────────┘"
echo ""
echo -e "  ┌─ WhatsApp Business ────────────────────┐"
echo -e "  │ ${M}Zira:${NC} Ahora vamos con WhatsApp            │"
echo -e "  │ ${M}Zira:${NC} Entrá a developers.facebook.com     │"
echo -e "  │ ${M}Zira:${NC} Creá una App nueva                 │"
echo -e "  │ ${M}Zira:${NC} Agregá WhatsApp Business           │"
echo -e "  │ ${M}Zira:${NC} Verificá tu número (te llega SMS)  │"
echo -e "  │ ${M}Zira:${NC} Creá una plantilla de mensaje      │"
echo -e "  │ ${M}Zira:${NC} Pegá la plantilla (te doy ejemplos)│"
echo -e "  │ ${G}✓ WhatsApp conectado ✓${NC}               │"
echo -e "  └─────────────────────────────────────────┘"
echo ""
echo -e "  ┌─ Instagram ────────────────────────────┐"
echo -e "  │ ${M}Zira:${NC} Vinculá Instagram a Facebook       │"
echo -e "  │ ${M}Zira:${NC} Habilitá Instagram Graph API       │"
echo -e "  │ ${M}Zira:${NC} Generá un token                   │"
echo -e "  │ ${G}✓ Instagram conectado ✓${NC}              │"
echo -e "  └─────────────────────────────────────────┘"
echo ""
echo -e "  ┌─ GitHub ───────────────────────────────┐"
echo -e "  │ ${M}Zira:${NC} Creá cuenta en github.com          │"
echo -e "  │ ${M}Zira:${NC} Generá un token personal          │"
echo -e "  │ ${M}Zira:${NC} Yo creo el repositorio            │"
echo -e "  │ ${G}✓ GitHub respaldando ✓${NC}              │"
echo -e "  └─────────────────────────────────────────┘"
echo ""
read -p "  → Todo configurado...  [Enter]"
echo ""

# ═══════════════════════════════════════════
# FASE 9: Resultado final
# ═══════════════════════════════════════════
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${B}  FASE 9: ¡CRM LISTO!${NC}"
echo -e "${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ╔══════════════════════════════════════════╗"
echo -e "  ║  🎉 ¡TU CRM ESTÁ FUNCIONANDO!            ║"
echo -e "  ╚══════════════════════════════════════════╝"
echo ""
echo -e "  ${G}✅ Google Sheets conectado${NC}"
echo -e "  ${G}✅ WhatsApp Business activo${NC}"
echo -e "  ${G}✅ Instagram configurado${NC}"
echo -e "  ${G}✅ GitHub respaldando${NC}"
echo -e "  ${G}✅ Zira asistiendo 24/7${NC}"
echo ""
echo -e "  Tu posada ahora puede:"
echo -e "  📱 Recibir reservas por WhatsApp"
echo -e "  📊 Actualizar precios desde el celular"
echo -e "  📸 Publicar en Instagram automáticamente"
echo -e "  🌐 Mantener tu página web actualizada"
echo -e "  🔒 Respaldar todo en GitHub"
echo ""
echo -e "  ══════════════════════════════════════════"
echo -e "  Tiempo total: ~4 horas"
echo -e "  Comandos ejecutados: 4"
echo -e "  Conocimiento técnico: 0"
echo -e "  ══════════════════════════════════════════"
echo ""
echo -e "  ${M}Zira:${NC} ¡Listo! Tu CRM está funcionando."
echo -e "        Si necesitás algo, escribime."
echo -e "        ¡Éxitos con tu posada! 🏔️"
echo ""
echo -e "${C}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${W}📧  ¿Todo funcionó? ¡Dejanos tu testimonio!${NC}"
echo -e "${W}🌐  Documentación: Abrí index.html${NC}"
echo -e "${C}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
