// SPDX-License-Identifier: MIT
// Generated by create-agent-harness — your harness's `curso-interactivo init` entry.

import { loadKernel } from '@metaharness/kernel';
import adapter from '@metaharness/host-hermes';

const HARNESS_NAME = 'curso-interactivo';

async function main(): Promise<number> {
  const kernel = await loadKernel();
  const info = kernel.kernelInfo();
  console.log(`${HARNESS_NAME} — kernel ${info.version} (${kernel.backend})`);
  console.log(`Host adapter: ${adapter.name}`);
  console.log(`Run \`${HARNESS_NAME} doctor\` to verify the install.`);
  return 0;
}

main().then(c => process.exit(c)).catch(err => {
  console.error(err);
  process.exit(1);
});
